---
- hosts: AgentVM
  become: yes
  vars:
    DOCKER_PACKAGES:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

  tasks:
    - name: 'Update apt-get repo'
      apt: #sudo apt-get update
        update_cache: yes
        force_apt_get: yes

    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes

#    - name: 'Install JDK 8'
#      apt: #sudo apt-get install default-jdk
#       name: openjdk-8-jdk
#       update_cache: yes

#    - name: 'Create Jenkins directory'
#      file: #/home/jenkinsagent
#       state: directory
#       path: /home/jenkinsagent
#       mode: '777'
#       recurse: yes

#    - name: 'Download JenkinsAgent file'
#      get_url: #wget http://10.0.0.4:8080/jnlpJars/agent.jar
#       url: http://10.0.0.4:8080/jnlpJars/agent.jar
#       dest: /home/jenkinsagent
#
#    - name: Installing Jenkins agent
#      shell: java -jar /home/jenkinsagent/agent.jar -jnlpUrl http://10.0.0.4:8080/computer/jenkinsagent/jenkins-agent.jnlp -secret c0b119c828349f612cf12789fe9898427128fe7ac1bf0a9f84f58e23c65562d7 -workDir "/home/jenkinsagent" &

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"
    - name: Install packages needed for Docker
      apt:
        name: "{{ DOCKER_PACKAGES }}"
        state: present
        force_apt_get: "yes"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Save the current Ubuntu release version into a variable
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker
      apt:
        name: "docker-ce"
        state: present
        force_apt_get: "yes"
